version: "3.9"

services:
  postgres:
    platform: linux/x86_64
    container_name: postgres
    image: localdev/postgres
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db-store-dev:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=password
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

volumes:
  db-store-dev:
